[ 2025-05-19 20:43:34,634 ] root - INFO - Entered the start_data_ingestion method of TrainPipeline class
[ 2025-05-19 20:43:34,635 ] root - INFO - Getting the data from mongodb
[ 2025-05-19 20:43:34,635 ] root - INFO - Entered initiate_data_ingestion method of Data_Ingestion class
[ 2025-05-19 20:43:34,635 ] root - INFO - Exporting data from mongodb
[ 2025-05-19 20:43:34,635 ] root - ERROR - Error occurred in python script: [/home/basavarajmadiwalar/Documents/projects/MLOPS/MLOPS-proj-2/src/configuration/mongo_db_connection.py] at line number [51]: Environment variable 'MONGODB_URL' is not set.
[ 2025-05-19 20:43:34,635 ] root - ERROR - Error occurred in python script: [/home/basavarajmadiwalar/Documents/projects/MLOPS/MLOPS-proj-2/src/data_access/proj1_data.py] at line number [20]: Error occurred in python script: [/home/basavarajmadiwalar/Documents/projects/MLOPS/MLOPS-proj-2/src/configuration/mongo_db_connection.py] at line number [51]: Environment variable 'MONGODB_URL' is not set.
[ 2025-05-19 20:43:34,635 ] root - ERROR - Error occurred in python script: [/home/basavarajmadiwalar/Documents/projects/MLOPS/MLOPS-proj-2/src/components/data_ingestion.py] at line number [34]: Error occurred in python script: [/home/basavarajmadiwalar/Documents/projects/MLOPS/MLOPS-proj-2/src/data_access/proj1_data.py] at line number [20]: Error occurred in python script: [/home/basavarajmadiwalar/Documents/projects/MLOPS/MLOPS-proj-2/src/configuration/mongo_db_connection.py] at line number [51]: Environment variable 'MONGODB_URL' is not set.
[ 2025-05-19 20:43:34,635 ] root - ERROR - Error occurred in python script: [/home/basavarajmadiwalar/Documents/projects/MLOPS/MLOPS-proj-2/src/components/data_ingestion.py] at line number [86]: Error occurred in python script: [/home/basavarajmadiwalar/Documents/projects/MLOPS/MLOPS-proj-2/src/components/data_ingestion.py] at line number [34]: Error occurred in python script: [/home/basavarajmadiwalar/Documents/projects/MLOPS/MLOPS-proj-2/src/data_access/proj1_data.py] at line number [20]: Error occurred in python script: [/home/basavarajmadiwalar/Documents/projects/MLOPS/MLOPS-proj-2/src/configuration/mongo_db_connection.py] at line number [51]: Environment variable 'MONGODB_URL' is not set.
[ 2025-05-19 20:43:34,635 ] root - ERROR - Error occurred in python script: [/home/basavarajmadiwalar/Documents/projects/MLOPS/MLOPS-proj-2/src/pipline/training_pipeline.py] at line number [47]: Error occurred in python script: [/home/basavarajmadiwalar/Documents/projects/MLOPS/MLOPS-proj-2/src/components/data_ingestion.py] at line number [86]: Error occurred in python script: [/home/basavarajmadiwalar/Documents/projects/MLOPS/MLOPS-proj-2/src/components/data_ingestion.py] at line number [34]: Error occurred in python script: [/home/basavarajmadiwalar/Documents/projects/MLOPS/MLOPS-proj-2/src/data_access/proj1_data.py] at line number [20]: Error occurred in python script: [/home/basavarajmadiwalar/Documents/projects/MLOPS/MLOPS-proj-2/src/configuration/mongo_db_connection.py] at line number [51]: Environment variable 'MONGODB_URL' is not set.
[ 2025-05-19 20:43:34,635 ] root - ERROR - Error occurred in python script: [/home/basavarajmadiwalar/Documents/projects/MLOPS/MLOPS-proj-2/src/pipline/training_pipeline.py] at line number [133]: Error occurred in python script: [/home/basavarajmadiwalar/Documents/projects/MLOPS/MLOPS-proj-2/src/pipline/training_pipeline.py] at line number [47]: Error occurred in python script: [/home/basavarajmadiwalar/Documents/projects/MLOPS/MLOPS-proj-2/src/components/data_ingestion.py] at line number [86]: Error occurred in python script: [/home/basavarajmadiwalar/Documents/projects/MLOPS/MLOPS-proj-2/src/components/data_ingestion.py] at line number [34]: Error occurred in python script: [/home/basavarajmadiwalar/Documents/projects/MLOPS/MLOPS-proj-2/src/data_access/proj1_data.py] at line number [20]: Error occurred in python script: [/home/basavarajmadiwalar/Documents/projects/MLOPS/MLOPS-proj-2/src/configuration/mongo_db_connection.py] at line number [51]: Environment variable 'MONGODB_URL' is not set.
